# Odyssey is FREE™
That being said, if you'd like to support me, your investment will directly help fund my music studio.
Equipment is expensive, so funds directly go towards repairs and expansion of hardware and software, for use in composition.
patreon: neoteaika
custom: ["paypal @ neoteaika@gmail.com"]
