# Odyssey is FREE™ That being said, if you'd like to support me, your investment will directly help fund my music studio.
# Just as the UNSC had a fleet of ships, I build up a fleet of synths, FX gear, software and other direct tools
# that add to an audio "canvas"
# Funds directly go towards repairs and expansion of hardware and software, for use in composition.
patreon: neoteaika
custom: ["Odyssey is FREE™ That being said,"]
custom: ["if you'd like to support me, your investment"]
custom: ["will directly help fund my music studio."]
custom: ["Just as the UNSC had a fleet of ships, I build up a fleet of synths,"]
custom: ["FX gear, software and other direct tools that add to the total canvas."]
custom: ["Donations directly contribute towards repairs & expansion of my tools, for use in composition."]
