# Odyssey is FREE™ That being said, if you'd like to support me, your investment will directly help fund my music studio.
# Just as the UNSC had a fleet of ships, I build up a fleet of synths, FX gear, software and other direct tools
# that add to an audio "canvas"
# Funds directly go towards repairs and expansion of hardware and software, for use in composition.
patreon: neoteaika
custom: ["paypal @ neoteaika@gmail.com"]
